### ISSUE TITLE
about training data

### ISSUE THREAD

**Issue by GuobinZhangTJU** [rotemgoren/VNET#1]
Hi, thanks for your sharing. Can you tell me the dataset you used for training?

**Comment by rotemgoren** [comment]
Dataset from Medical Segmentation Decathlon competitions : http://medicaldecathlon.com/ https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2

**Comment by GuobinZhangTJU** [comment]
Thanks for your reply, however, I can not open those two links using Google~~can you check the links again? thanks a lot~

**Comment by GuobinZhangTJU** [comment]
OMG~I'm sorry to bother you again, the links are working now~ my fault~

**Comment by GuobinZhangTJU** [comment]
OMG, I'm sorry to bother you again, the links are working now, my fault~
